/* Acronis MSP Platform — Tickets / Service Desk */

// ── CONFIG ──────────────────────────────────────────────────────

const TICKET_COLUMNS = [
  { id: 'new',         label: 'New' },
  { id: 'queued',      label: 'Queued' },
  { id: 'in-progress', label: 'In Progress' },
  { id: 'waiting',     label: 'Waiting' },
  { id: 'resolved',    label: 'Resolved' },
];

const PRIORITY_MAP = {
  p1: { label: 'P1', text: 'Critical' },
  p2: { label: 'P2', text: 'High' },
  p3: { label: 'P3', text: 'Normal' },
  p4: { label: 'P4', text: 'Low' },
};

const TYPE_ICON  = { alert: '🔔', incident: '🔧', request: '📥', task: '✅', maintenance: '🗓️' };
const TYPE_LABEL = { alert: 'Alert', incident: 'Incident', request: 'Request', task: 'Task', maintenance: 'Maintenance' };
const SOURCE_ICON  = { auto: '🤖', manual: '👤' };
const SOURCE_LABEL = { auto: 'Auto-generated', manual: 'Manual' };
const COLUMN_LABEL = { 'new': 'New', 'queued': 'Queued', 'in-progress': 'In Progress', 'waiting': 'Waiting', 'resolved': 'Resolved' };

// ── TICKET DATA ─────────────────────────────────────────────────

const TICKETS = [
  // ── NEW ────────────────────────────────────────────────────
  {
    id: 'TKT-0041', priority: 'p2', source: 'auto', type: 'alert', status: 'new',
    title: 'WIN-SALES-02 elevated CPU',
    client: 'Metro Auto Group', clientId: 3, device: 'WIN-SALES-02', deviceId: 302,
    context: 'CPU 77%, memory 84%. Threshold breach auto-generated.',
    age: '34m', assignee: null,
    created: '2026-04-30 09:26',
    description: 'Device WIN-SALES-02 at Metro Auto Group has been reporting elevated CPU (77%) and memory (84%) for the past 30 minutes. Auto-generated by RMM monitoring threshold breach. No client impact reported yet.',
    activity: [
      { ts: '2026-04-30 09:26', type: 'warn', title: 'Ticket auto-created', body: 'CPU > 75% for 15+ minutes. Memory > 80% simultaneously.' },
    ],
  },
  {
    id: 'TKT-0042', priority: 'p3', source: 'manual', type: 'request', status: 'new',
    title: 'Add new employee laptop — Pinnacle CPA',
    client: 'Pinnacle CPA', clientId: 4, device: null, deviceId: null,
    context: 'New hire starts May 5. Agent, backup, and policy enrollment needed.',
    age: '1h', assignee: null,
    created: '2026-04-30 08:52',
    description: 'Client contact at Pinnacle CPA emailed requesting onboarding for a new hire starting May 5. Standard laptop setup: RMM agent install, backup enrollment, Windows Update Baseline policy apply, admin account creation.',
    activity: [
      { ts: '2026-04-30 08:52', type: 'info', title: 'Request received via email', body: 'Client emailed requesting new device onboarding for May 5 start date.' },
    ],
  },

  // ── QUEUED ─────────────────────────────────────────────────
  {
    id: 'TKT-0038', priority: 'p2', source: 'manual', type: 'task', status: 'queued',
    title: 'Admin credential rotation — server fleet',
    client: 'All Clients', clientId: null, device: null, deviceId: null,
    context: '3 servers due within 7 days per policy. SRV-DC-01, SRV-APPS-01, SRV-FILES-01.',
    age: '2d', assignee: 'JC',
    created: '2026-04-28 14:00',
    description: 'Admin Credential Rotation policy flags 3 servers as due within 7 days. Manual rotation required: SRV-DC-01 (Riverside Dental), SRV-APPS-01 (Metro Auto), SRV-FILES-01 (Harbor Legal). Update credentials in vault after each rotation.',
    activity: [
      { ts: '2026-04-28 14:00', type: 'info', title: 'Task created from policy', body: 'Admin Credential Rotation policy triggered this task — 3 servers due within 7 days.' },
      { ts: '2026-04-29 09:00', type: 'info', title: 'Moved to Queued', body: 'Prioritized for this week. Assigned to JC.' },
    ],
  },
  {
    id: 'TKT-0039', priority: 'p3', source: 'manual', type: 'task', status: 'queued',
    title: 'Metro Auto — XDR quote follow-up',
    client: 'Metro Auto Group', clientId: 3, device: null, deviceId: null,
    context: 'XDR upgrade quote sent Apr 28. No approval yet. Nudge call due.',
    age: '1d', assignee: 'JC',
    created: '2026-04-29 10:00',
    description: 'Metro Auto Group received XDR Security Upgrade quote on Apr 28 (+$558/mo). Quote still awaiting approval. Follow up with primary contact to understand blockers. If approved, XDR deployment can proceed immediately via Policies.',
    activity: [
      { ts: '2026-04-29 10:00', type: 'info', title: 'Follow-up task created', body: 'XDR quote pending. Nudge call scheduled for Apr 30.' },
    ],
  },

  // ── IN PROGRESS ────────────────────────────────────────────
  {
    id: 'TKT-0035', priority: 'p1', source: 'auto', type: 'alert', status: 'in-progress',
    title: 'WIN-SERVICE-01 critical — CPU + backup failure',
    client: 'Metro Auto Group', clientId: 3, device: 'WIN-SERVICE-01', deviceId: 303,
    context: 'CPU 99%, disk 88%, backup missed Apr 26. Cleanup automation running.',
    age: '3h', assignee: 'JC',
    created: '2026-04-30 07:14',
    description: 'Critical alert on WIN-SERVICE-01 at Metro Auto Group. QuickBooks database process (QuickBooksDB27) identified as root cause — running unchecked since approx. Apr 26 05:00 AM. Disk at 88%, insufficient headroom for backup snapshot. Disk cleanup automation was triggered manually at 07:22 AM.',
    activity: [
      { ts: '2026-04-30 07:14', type: 'warn', title: 'Critical alert triggered', body: 'CPU > 95% and disk > 85% thresholds breached simultaneously.' },
      { ts: '2026-04-30 07:22', type: 'info', title: 'Root cause identified', body: 'QuickBooksDB27 consuming 9,841 CPU seconds. Running unchecked since Apr 26.' },
      { ts: '2026-04-30 07:22', type: 'success', title: 'Disk cleanup automation triggered', body: 'Manual run initiated. Freeing space to allow backup snapshot.' },
      { ts: '2026-04-30 09:00', type: 'info', title: 'Monitoring', body: 'CPU recovering. Cleanup in progress. Backup agent reconnecting.' },
    ],
  },
  {
    id: 'TKT-0037', priority: 'p2', source: 'auto', type: 'alert', status: 'in-progress',
    title: 'WIN-BILLING-01 disk critical — Riverside Dental',
    client: 'Riverside Dental Group', clientId: 1, device: 'WIN-BILLING-01', deviceId: 106,
    context: 'Disk 91%, backup failed Apr 27. Space investigation underway.',
    age: '5h', assignee: 'JC',
    created: '2026-04-30 05:00',
    description: 'WIN-BILLING-01 at Riverside Dental hit 91% disk. Backup snapshot failed Apr 27 at 04:00 AM — insufficient space. Root cause: QuickBooksBackup.qbb (2.1 GB) stored locally instead of on the network share. Client has been notified to coordinate file relocation.',
    activity: [
      { ts: '2026-04-30 05:00', type: 'warn', title: 'Backup failed — disk full', body: 'Backup agent reported insufficient space for snapshot. Disk at 91%.' },
      { ts: '2026-04-30 07:30', type: 'info', title: 'Root cause found', body: '2.1 GB QuickBooksBackup.qbb stored locally — should be on network share.' },
      { ts: '2026-04-30 08:00', type: 'info', title: 'Client notified', body: 'Emailed billing@rdg.com. Awaiting callback to coordinate file move.' },
    ],
  },

  // ── WAITING ────────────────────────────────────────────────
  {
    id: 'TKT-0033', priority: 'p3', source: 'auto', type: 'incident', status: 'waiting',
    title: 'WIN-DR-OFFICE-01 high CPU — awaiting client',
    client: 'Riverside Dental Group', clientId: 1, device: 'WIN-DR-OFFICE-01', deviceId: 102,
    context: 'Imaging software scan causing CPU spike. Waiting on Dr. Patel to schedule maintenance window.',
    age: '1d', assignee: 'JC',
    created: '2026-04-29 11:02',
    description: 'WIN-DR-OFFICE-01 (Dr. Patel\'s workstation) showing sustained CPU elevation at 88% due to Dexis Imaging Suite running a large scan. Expected behavior but degrading performance. Client asked to confirm a maintenance window for software reconfiguration.',
    activity: [
      { ts: '2026-04-29 11:02', type: 'warn', title: 'High CPU alert', body: 'CPU at 88% for 30+ minutes. Dexis imaging scan identified as cause.' },
      { ts: '2026-04-29 14:32', type: 'info', title: 'Client notified', body: 'Notified Dr. Patel. Requested maintenance window for imaging reconfiguration.' },
      { ts: '2026-04-30 08:00', type: 'info', title: 'Moved to Waiting', body: 'No client response yet. Following up this afternoon.' },
    ],
  },

  // ── HIDDEN (injected by flows only) ───────────────────────
  {
    id: 'TKT-0043', priority: 'p3', source: 'auto', type: 'task', status: '_hidden',
    title: 'New Client Onboarding — Sunrise Bakery',
    client: 'Sunrise Bakery', clientId: null, device: null, deviceId: null,
    context: 'Contract signed Apr 29 9:34 AM. 12 devices pending enrollment.',
    age: '0m', assignee: null,
    created: '2026-04-29 09:34',
    description: 'New client signed. Onboarding policy triggered — device enrollment instructions sent to lisa@sunrisebakery.com. Work through: RMM agent install on 12 devices, backup enrollment, Windows Update Baseline policy application.',
    activity: [
      { ts: '2026-04-29 09:34', type: 'info', title: 'Auto-created on contract signature', body: 'Sunrise Bakery MSA signed. New Client Onboarding policy triggered this task.' },
    ],
  },

  // ── RESOLVED ───────────────────────────────────────────────
  {
    id: 'TKT-0030', priority: 'p2', source: 'auto', type: 'alert', status: 'resolved',
    title: 'SRV-APPS-02 memory pressure — Metro Auto',
    client: 'Metro Auto Group', clientId: 3, device: 'SRV-APPS-02', deviceId: 305,
    context: 'RAM at 79%, resolved by restarting application service.',
    age: '', assignee: 'JC',
    created: '2026-04-28 15:00', resolvedAt: '2026-04-28 18:14',
    description: 'SRV-APPS-02 at Metro Auto hit 79% memory utilization. Application service restart freed 4 GB of RAM. Monitoring for recurrence.',
    activity: [
      { ts: '2026-04-28 15:00', type: 'warn', title: 'Memory pressure alert', body: 'RAM at 79%.' },
      { ts: '2026-04-28 18:10', type: 'info', title: 'Application service restarted', body: 'Service restart freed 4 GB RAM.' },
      { ts: '2026-04-28 18:14', type: 'success', title: 'Resolved', body: 'Memory stable at 61%. Ticket closed.' },
    ],
  },
  {
    id: 'TKT-0031', priority: 'p1', source: 'manual', type: 'incident', status: 'resolved',
    title: 'Harbor Legal — email outage (DNS misconfiguration)',
    client: 'Harbor Legal Group', clientId: 2, device: null, deviceId: null,
    context: 'Total outage 11:30–12:45 PM. DNS MX record corrected. Postmortem filed.',
    age: '', assignee: 'JC',
    created: '2026-04-27 11:30', resolvedAt: '2026-04-27 12:45',
    description: 'Total email outage at Harbor Legal Group from 11:30 AM to 12:45 PM. Root cause: MX record missing after DNS provider migration. Record corrected manually. Postmortem note filed in client notes log.',
    activity: [
      { ts: '2026-04-27 11:30', type: 'warn', title: 'Email outage reported', body: 'Client called — no inbound or outbound email. All staff affected.' },
      { ts: '2026-04-27 11:45', type: 'info', title: 'Root cause: DNS MX record', body: 'MX record missing after DNS provider migration.' },
      { ts: '2026-04-27 12:44', type: 'success', title: 'DNS record corrected', body: 'MX record updated and propagated.' },
      { ts: '2026-04-27 12:45', type: 'success', title: 'Resolved', body: 'Email restored. Client confirmed. Postmortem note filed.' },
    ],
  },
];

// ── DRAG-AND-DROP NOTE TEMPLATES ────────────────────────────────
// Keyed on destination column only — generic enough to apply to any ticket.

const COLUMN_NOTE_TEMPLATES = {
  'new':
    'Ticket returned to New for re-triage. Previous work log preserved. Reassign priority as needed before re-queuing.',
  'queued':
    'Ticket reviewed and triaged. Priority confirmed. Queued for scheduled work — no immediate action required.',
  'in-progress':
    'Taking ownership of this ticket. Initial assessment complete. Beginning active remediation.',
  'waiting':
    'Work paused. Blocked pending external response or access. Will follow up and resume once unblocked.',
  'resolved':
    'Issue resolved. Root cause identified and addressed. No further action required at this time. Closing ticket.',
};

// ── RENDER ──────────────────────────────────────────────────────

let _ticketView = 'kanban'; // 'kanban' | 'list'

function setTicketView(v) { _ticketView = v; renderTickets(); }

function renderTickets() {
  const panel = document.getElementById('panel-tickets');
  panel.classList.add('active');

  const openCount     = TICKETS.filter(t => t.status !== 'resolved').length;
  const criticalCount = TICKETS.filter(t => ['p1','p2'].includes(t.priority) && t.status !== 'resolved').length;

  const viewToggle = `
    <div class="tkt-view-toggle">
      <button class="tkt-view-btn ${_ticketView === 'kanban' ? 'active' : ''}" onclick="setTicketView('kanban')" title="Board view">
        <svg width="14" height="14" viewBox="0 0 14 14" fill="currentColor">
          <rect x="0" y="0" width="4" height="14" rx="1"/>
          <rect x="5" y="0" width="4" height="14" rx="1"/>
          <rect x="10" y="0" width="4" height="14" rx="1"/>
        </svg>
        Board
      </button>
      <button class="tkt-view-btn ${_ticketView === 'list' ? 'active' : ''}" onclick="setTicketView('list')" title="List view">
        <svg width="14" height="14" viewBox="0 0 14 14" fill="currentColor">
          <rect x="0" y="0"  width="14" height="2.5" rx="1"/>
          <rect x="0" y="4"  width="14" height="2.5" rx="1"/>
          <rect x="0" y="8"  width="14" height="2.5" rx="1"/>
          <rect x="0" y="12" width="14" height="2.5" rx="1"/>
        </svg>
        List
      </button>
    </div>`;

  const filters = `
    <select class="form-select" style="width:auto;font-size:12px;padding:5px 8px">
      <option>All clients</option>
      ${[...new Set(TICKETS.filter(t=>t.clientId).map(t=>t.client))].map(c=>`<option>${c}</option>`).join('')}
    </select>
    <select class="form-select" style="width:auto;font-size:12px;padding:5px 8px">
      <option>All types</option>
      <option>Alert</option><option>Incident</option><option>Request</option><option>Task</option><option>Maintenance</option>
    </select>
    <select class="form-select" style="width:auto;font-size:12px;padding:5px 8px">
      <option>All priorities</option>
      <option>P1 Critical</option><option>P2 High</option><option>P3 Normal</option><option>P4 Low</option>
    </select>
    <button class="btn btn-primary btn-sm">+ New Ticket</button>`;

  const header = `
    <div class="page-header">
      <div>
        <div class="page-title">Tickets</div>
        <div class="page-subtitle">${criticalCount} critical (P1/P2) &nbsp;·&nbsp; ${openCount} open</div>
      </div>
      <div class="page-actions">
        ${viewToggle}
        ${filters}
      </div>
    </div>`;

  if (_ticketView === 'kanban') {
    // Group by status
    const byStatus = {};
    TICKET_COLUMNS.forEach(c => { byStatus[c.id] = []; });
    TICKETS.forEach(t => { if (byStatus[t.status]) byStatus[t.status].push(t); });

    panel.innerHTML = header + `
      <div class="kanban-wrap">
        <div class="kanban-board">
          ${TICKET_COLUMNS.map(col => `
            <div class="kanban-col ${col.id === 'resolved' ? 'kanban-col-resolved' : ''}" data-status="${col.id}">
              <div class="kanban-col-header">
                <span class="kanban-col-title">${col.label}</span>
                <span class="kanban-col-count">${byStatus[col.id].length}</span>
                <button class="kanban-col-rename" title="Rename column">✎</button>
              </div>
              <div class="kanban-col-cards">
                ${byStatus[col.id].map(t => renderTicketCard(t)).join('') || '<div class="kanban-col-empty">—</div>'}
              </div>
            </div>
          `).join('')}
        </div>
      </div>`;

    initKanbanDragDrop();

  } else {
    // Sort: open first (by priority p1→p4), then resolved
    const sorted = [...TICKETS].sort((a, b) => {
      const statusOrder = ['in-progress','new','queued','waiting','resolved'];
      const prioOrder   = ['p1','p2','p3','p4'];
      const sd = statusOrder.indexOf(a.status) - statusOrder.indexOf(b.status);
      if (sd !== 0) return sd;
      return prioOrder.indexOf(a.priority) - prioOrder.indexOf(b.priority);
    });

    panel.innerHTML = header + `
      <div class="page-body">
        <div class="table-wrap">
          <table class="data-table">
            <thead>
              <tr>
                <th>ID</th>
                <th>Priority</th>
                <th>Title</th>
                <th>Client</th>
                <th>Type</th>
                <th>Status</th>
                <th>Assignee</th>
                <th>Age</th>
              </tr>
            </thead>
            <tbody>
              ${sorted.map(t => {
                const p = PRIORITY_MAP[t.priority];
                const age = t.status === 'resolved' ? t.resolvedAt?.split(' ')[0] : (t.age + ' ago');
                return `
                  <tr onclick="openTicketDrawer('${t.id}')" style="${t.status === 'resolved' ? 'opacity:0.6' : ''}">
                    <td style="font-family:var(--font-mono);font-size:11px;color:var(--text-4)">${t.id}</td>
                    <td><span class="tkt-priority tkt-${t.priority}" style="white-space:nowrap">${p.label} ${p.text}</span></td>
                    <td class="td-name" style="max-width:260px">${t.title}</td>
                    <td class="text-muted">${t.client}</td>
                    <td style="white-space:nowrap">${SOURCE_ICON[t.source]} ${TYPE_ICON[t.type]} <span style="font-size:11px;color:var(--text-3)">${TYPE_LABEL[t.type]}</span></td>
                    <td><span class="badge badge-${t.status === 'resolved' ? 'green' : t.status === 'waiting' ? 'yellow' : t.status === 'in-progress' ? 'blue' : 'gray'}">${COLUMN_LABEL[t.status]}</span></td>
                    <td>${t.assignee ? `<span class="tkt-assignee-chip">${t.assignee}</span>` : '<span style="color:var(--text-4)">—</span>'}</td>
                    <td style="font-size:12px;color:var(--text-4);white-space:nowrap">${age}</td>
                  </tr>`;
              }).join('')}
            </tbody>
          </table>
        </div>
      </div>`;
  }
}

function renderTicketCard(t) {
  const p = PRIORITY_MAP[t.priority];
  const footer = t.status === 'resolved'
    ? `<span style="color:var(--text-4)">${t.resolvedAt?.split(' ')[0]}</span>`
    : `<span style="color:var(--text-4)">${t.age} ago</span>`;
  const assignee = t.assignee
    ? `<span class="tkt-assignee-chip">${t.assignee}</span>`
    : `<span style="color:var(--text-4)">Unassigned</span>`;

  return `
    <div class="tkt-card" draggable="true" data-id="${t.id}" onclick="openTicketDrawer('${t.id}')">
      <div class="tkt-card-top">
        <span class="tkt-priority tkt-${t.priority}">${p.label} ${p.text}</span>
        <div class="tkt-icons" title="${SOURCE_LABEL[t.source]} · ${TYPE_LABEL[t.type]}">
          ${SOURCE_ICON[t.source]} ${TYPE_ICON[t.type]}
        </div>
      </div>
      <div class="tkt-title">${t.title}</div>
      <div class="tkt-meta">${t.client}</div>
      <div class="tkt-context">${t.context}</div>
      <div class="tkt-footer">
        ${assignee}
        ${footer}
      </div>
    </div>
  `;
}

// ── DRAWER ──────────────────────────────────────────────────────

function openTicketDrawer(id) {
  const t = TICKETS.find(t => t.id === id);
  if (!t) return;
  const p = PRIORITY_MAP[t.priority];

  const contextRows = [
    `<div style="display:flex;gap:10px;font-size:13px">
       <span class="text-muted" style="min-width:56px;flex-shrink:0">Client</span>
       ${t.clientId
         ? `<button class="btn btn-ghost btn-sm" style="padding:0;font-size:13px;height:auto" onclick="closeTicketDrawer();navigate('client/${t.clientId}')">${t.client} →</button>`
         : `<span>${t.client}</span>`}
     </div>`,
    t.device ? `<div style="display:flex;gap:10px;font-size:13px">
       <span class="text-muted" style="min-width:56px;flex-shrink:0">Device</span>
       <button class="btn btn-ghost btn-sm" style="padding:0;font-size:13px;height:auto" onclick="closeTicketDrawer();navigate('device/${t.deviceId}')">${t.device} →</button>
     </div>` : '',
    `<div style="display:flex;gap:10px;font-size:13px">
       <span class="text-muted" style="min-width:56px;flex-shrink:0">Opened</span>
       <span>${t.created}</span>
     </div>`,
    t.resolvedAt ? `<div style="display:flex;gap:10px;font-size:13px">
       <span class="text-muted" style="min-width:56px;flex-shrink:0">Resolved</span>
       <span>${t.resolvedAt}</span>
     </div>` : '',
  ].filter(Boolean).join('');

  const moveOptions = TICKET_COLUMNS
    .filter(c => c.id !== t.status)
    .map(c => `<option value="${c.id}">${c.label}</option>`)
    .join('');

  document.getElementById('ticket-drawer-inner').innerHTML = `
    <div class="ticket-drawer-header-bar">
      <div style="min-width:0">
        <div class="ticket-drawer-id">${t.id} &nbsp;·&nbsp; ${t.created}</div>
        <div class="ticket-drawer-title">${t.title}</div>
      </div>
      <button class="modal-close" onclick="closeTicketDrawer()" style="flex-shrink:0">✕</button>
    </div>

    <div class="ticket-drawer-body">

      <div class="ticket-drawer-meta-row">
        <span class="tkt-priority tkt-${t.priority}">${p.label} ${p.text}</span>
        <span class="badge badge-gray">${SOURCE_ICON[t.source]} ${SOURCE_LABEL[t.source]}</span>
        <span class="badge badge-gray">${TYPE_ICON[t.type]} ${TYPE_LABEL[t.type]}</span>
        <span class="badge badge-blue">${COLUMN_LABEL[t.status]}</span>
        ${t.assignee ? `<span class="tkt-assignee-chip">${t.assignee}</span>` : '<span style="font-size:12px;color:var(--text-4)">Unassigned</span>'}
      </div>

      <div class="ticket-drawer-section">
        <div class="ticket-drawer-section-label">Context</div>
        <div style="display:flex;flex-direction:column;gap:6px">${contextRows}</div>
      </div>

      <div class="ticket-drawer-section">
        <div class="ticket-drawer-section-label">Description</div>
        <p style="font-size:13px;color:var(--text-2);line-height:1.65">${t.description}</p>
      </div>

      <div class="ticket-drawer-section" style="flex:1">
        <div class="ticket-drawer-section-label">Activity</div>
        <div class="timeline">
          ${t.activity.map(a => `
            <div class="timeline-item">
              <div class="timeline-dot ${a.type === 'warn' ? 'warn' : a.type === 'success' ? 'success' : ''}"></div>
              <div class="timeline-ts">${a.ts}</div>
              <div class="timeline-body">
                <strong>${a.title}</strong>
                <p>${a.body}</p>
              </div>
            </div>
          `).join('')}
        </div>
      </div>

    </div>

    <div class="ticket-drawer-footer">
      <select class="form-select" style="font-size:12px;padding:5px 8px;flex:1" onchange="moveTicket('${t.id}',this.value)">
        <option value="">Move to…</option>
        ${moveOptions}
      </select>
      <button class="btn btn-secondary btn-sm">Add Note</button>
      ${['p3','p4'].includes(t.priority) ? `<button class="btn btn-primary btn-sm">Escalate</button>` : ''}
    </div>
  `;

  document.getElementById('ticket-drawer-overlay').style.display = 'block';
  document.getElementById('ticket-drawer').style.display = 'flex';
}

function closeTicketDrawer() {
  document.getElementById('ticket-drawer-overlay').style.display = 'none';
  document.getElementById('ticket-drawer').style.display = 'none';
}

// ── DRAG AND DROP ────────────────────────────────────────────────

let _dragTicketId  = null;
let _dragDestStatus = null;

function initKanbanDragDrop() {
  document.querySelectorAll('.tkt-card').forEach(card => {
    card.addEventListener('dragstart', _onDragStart);
    card.addEventListener('dragend',   _onDragEnd);
  });
  document.querySelectorAll('.kanban-col').forEach(col => {
    col.addEventListener('dragover',  _onDragOver);
    col.addEventListener('dragleave', _onDragLeave);
    col.addEventListener('drop',      _onDrop);
  });
}

function _onDragStart(e) {
  _dragTicketId = e.currentTarget.dataset.id;
  e.dataTransfer.effectAllowed = 'move';
  e.dataTransfer.setData('text/plain', _dragTicketId);
  // Delay so the ghost image captures the un-faded card
  setTimeout(() => e.currentTarget.classList.add('dragging'), 0);
}

function _onDragEnd(e) {
  e.currentTarget.classList.remove('dragging');
  document.querySelectorAll('.kanban-col').forEach(c => c.classList.remove('drag-over'));
}

function _onDragOver(e) {
  e.preventDefault();
  e.dataTransfer.dropEffect = 'move';
  e.currentTarget.classList.add('drag-over');
}

function _onDragLeave(e) {
  // Only fire if leaving the column itself, not a child element
  if (!e.currentTarget.contains(e.relatedTarget)) {
    e.currentTarget.classList.remove('drag-over');
  }
}

function _onDrop(e) {
  e.preventDefault();
  e.currentTarget.classList.remove('drag-over');
  const destStatus = e.currentTarget.dataset.status;
  const ticket = TICKETS.find(t => t.id === _dragTicketId);
  if (!ticket || !destStatus || ticket.status === destStatus) {
    _dragTicketId = null;
    return;
  }
  _dragDestStatus = destStatus;
  _showDragNoteModal(ticket, destStatus);
}

function _showDragNoteModal(ticket, destStatus) {
  const srcLabel  = COLUMN_LABEL[ticket.status];
  const destLabel = COLUMN_LABEL[destStatus];
  document.getElementById('drag-note-title').textContent    = `Moving to ${destLabel}`;
  document.getElementById('drag-note-subtitle').textContent = `${ticket.id} · ${srcLabel} → ${destLabel}`;
  document.getElementById('drag-note-text').value           = COLUMN_NOTE_TEMPLATES[destStatus] || '';
  document.getElementById('drag-note-modal').style.display  = 'flex';
  // Select all text so the tech can start typing immediately to replace
  setTimeout(() => {
    const ta = document.getElementById('drag-note-text');
    ta.focus();
    ta.select();
  }, 80);
}

function confirmDragMove() {
  const ticket = TICKETS.find(t => t.id === _dragTicketId);
  if (!ticket || !_dragDestStatus) return;
  const noteText  = document.getElementById('drag-note-text').value.trim() || COLUMN_NOTE_TEMPLATES[_dragDestStatus];
  const destLabel = COLUMN_LABEL[_dragDestStatus];
  ticket.activity.push({
    ts:    new Date().toISOString().slice(0,16).replace('T',' '),
    type:  _dragDestStatus === 'resolved' ? 'success' : 'info',
    title: `Moved to ${destLabel}`,
    body:  noteText,
  });
  ticket.status = _dragDestStatus;
  if (_dragDestStatus === 'resolved') ticket.resolvedAt = new Date().toISOString().slice(0,16).replace('T',' ');
  cancelDragMove();
  renderTickets();
  // Auto-advance the guided flow if one is active
  if (typeof activeFlow !== 'undefined' && activeFlow) {
    document.getElementById('flow-bar').style.display = 'block';
    document.querySelector('.content').style.paddingBottom = '80px';
    setTimeout(() => flowNext(), 120);
  }
}

function cancelDragMove() {
  document.getElementById('drag-note-modal').style.display = 'none';
  _dragTicketId   = null;
  _dragDestStatus = null;
  // If cancelled during a guided flow, restore the narration bar
  if (typeof activeFlow !== 'undefined' && activeFlow) {
    document.getElementById('flow-bar').style.display = 'block';
    document.querySelector('.content').style.paddingBottom = '80px';
  }
}

function moveTicket(id, newStatus) {
  if (!newStatus) return;
  const t = TICKETS.find(t => t.id === id);
  if (!t) return;
  closeTicketDrawer();
  _dragTicketId   = id;
  _dragDestStatus = newStatus;
  _showDragNoteModal(t, newStatus);
}
